<?php
echo $section_title;
echo '<div id="page">';
echo validation_errors();
echo form_open_multipart('enquiries/outbound/process_add/', array('id' => 'outbound_add_form'));
print_form_container_open();
echo form_hidden('enquiry_id', set_value('enquiry_id'));
print_dropdown_element('enquiry_prefill', 'Enquiry Ref No.', $dropdowns['enquiries'], false, 'onchange="window.location=\'/enquiries/outbound/add/\'+$(this).val();"');
print_static_form_element('Enquirer Name', set_value('company_name'));
print_static_form_element('Enquirer Address 1', set_value('address_address1'));
print_static_form_element('Enquirer Address 2', set_value('address_address2'));
print_static_form_element('City', set_value('address_city'));
print_static_form_element('Province/State/County', set_value('address_state'));
print_static_form_element('Post Code', set_value('address_postcode'));
print_static_form_element('Country', set_value('address_country_id'));
print_static_form_element('Contact Title', set_value('user_salutation'));
print_static_form_element('Contact First Name', set_value('user_first_name'));
print_static_form_element('Contact Last Name', set_value('user_surname'));
print_static_form_element('Quotation Number', $next_id);
print_static_form_element('Quotation Date', unix_to_human(mktime()));
print_input_element('Product Title', array('name' => 'enquiry_product_title'));
print_textarea_element('Product Description', array('name' => 'enquiry_product_description', 'cols' => 80, 'rows' => 6));
print_textarea_element('Materials', array('name' => 'enquiry_product_materials', 'cols' => 30, 'rows' => 2));
print_textarea_element('Manufacturing Process', array('name' => 'enquiry_product_man_process', 'cols' => 30, 'rows' => 2));
print_input_element('Size', array('name' => 'enquiry_product_size'));
print_input_element('Weight', array('name' => 'enquiry_product_weight'));
print_input_element('Colour', array('name' => 'enquiry_product_colour'));
print_textarea_element('Packaging', array('name' => 'enquiry_product_packaging', 'cols' => 30, 'rows' => 4));
print_input_element('Product Lead Time', array('name' => 'quotation_product_lead_time'));
print_input_element('Tool Lead Time', array('name' => 'quotation_tool_lead_time'));
print_input_element('Tool Cost', array('name' => 'quotation_tool_cost'));
print_textarea_element('Notes', array('name' => 'quotation_notes', 'cols' => 30, 'rows' => 2));
print_input_element('Price', array('name' => 'quotation_price'));
print_input_element('Unit', array('name' => 'quotation_unit'));
print_dropdown_element('enquiry_currency', 'Currency', $dropdowns['currencies']);
print_input_element('Minimum Order Qty', array('name' => 'quotation_min_qty'), true);
print_dropdown_element('quotation_freight', 'Freight Type', $dropdowns['shipping_methods'], true);
print_dropdown_element('quotation_delivery_terms', 'Delivery Terms', $dropdowns['delivery_terms'], true);
print_dropdown_element('quotation_country_id', 'Delivery Country', $dropdowns['countries'], true);
print_input_element('Delivery Point', array('name' => 'quotation_delivery_point'), true);
print_dropdown_element('quotation_payment_terms', 'Payment Terms', $dropdowns['payment_terms']);
print_dropdown_element('quotation_tool_cost_payment_terms', 'Tool Cost Payment Terms', $dropdowns['tool_payment_terms']);
print_input_element('Sample Cost', array('name' => 'quotation_sample_cost'));
print_input_element('Sample Lead Time (Days)', array('name' => 'quotation_sample_time'));
print_input_element('Sample Payment Terms', array('name' => 'quotation_sample_payment_terms'));
print_dropdown_element('quotation_staff_id', 'Submitting Staff', $dropdowns['staff_list']);

print_submit_container_open();
echo form_submit('button', 'Submit', 'id="submit_button"');
print_submit_container_close();
print_form_container_close();
echo form_close();
echo '</div>';
